### ISSUE TITLE
[SD-JWT aggregation during Presentation] SD-JWT-R for multiple SD-JWT

### ISSUE THREAD

**Issue by peppelinux** [oauth-wg/oauth-selective-disclosure-jwt#114]
An Holder has two different JWT VCs issued by two different issuers and wants to disclose part of the attributes contained in these VCs in in a single Presentation.

Using Combined Presentation only a single SD-JWT with a single SD-JWT-R can be submitted (if I'm not mistaken).

Can we consider a way to redefine the Combined Presentation to allow multiple SD-JWTs to be submitted with a single SD-JWT-R?

**Comment by danielfett** [comment]
This is a relevant use case, but may also be addressed by the protocol used for presentation. @tlodderstedt What's your opinion on this?

**Comment by tlodderstedt** [comment]
There are protocols for carrying multiple presentation in the same exchange, so this use case can be solved on the protocol level.

However, I think there is some beauty in combined presentations. Combined presentation reduces the number of signatures to be created and checked for holder authentication/cryptographic holder binding and also requires the verifier to check audience restriction and transaction integrity once. On the other hand, it requires binding of both (or all) credentials to the same key material. So it seems to be an attractive feature, I cannot assess how relevant it is in practice and whether it causes complexity in other places.

**Comment by Sakurann** [comment]
I would make it simpler, <SD-JWT-1 (3 parts)>.<...>.<SD-JWT-n>.<SD-JWT-R> without any nesting.
so the key would be to define how to include sd_digests for multiple SD-JWTs in one SD-JWT-R
and it should be made clear that this is the case when SD-JWT-R is not signed - ie, there is no holder binding; or, SD-JWT-R is signed but SD-JWTs are bound to the same holder key.

**Comment by Sakurann** [comment]
What I meant by the second comment was multiple “sd_release”s in on SD-JWT-R. Which is sent separately from SD-JWTs. “sd_digests” was a typo, sorry

**Comment by peppelinux** [comment]
> What I meant by the second comment was multiple “sd_release”s in on SD-JWT-R. Which is sent separately from SD-JWTs. “sd_digests” was a typo, sorry

yes, a SD-JWT-R which contains multiple SD-JWT in an array, I think that's the key!

**Comment by Sakurann** [comment]
but than we would need to include `id` or something inside `sd_release`s so that the verifier knows which release to use with which  SD-JWT...

+ for a general direction I am not suggesting to put SD-JWTs inside Releases, Release is still sent separately.. Though SD-JWT-VCs will be inside SD-JWT-R-VPs

**Comment by peppelinux** [comment]
Ok, my concern Is that implementing a parser of multiple concatenated jwts can be a pain and this solution sounds more like a compromise

Consider that a jwt could be encrypted, having more thank 3strings separated by a period chat

For these reason I'd prefer a jwt that contains One or more sd-jwts, in a intellegibile claim, and a single sd_release

**Comment by danielfett** [comment]
> Consider that a jwt could be encrypted, having more thank 3strings separated by a period char

That's why I proposed to introduce a generic character to separate concatenated JWT in the very beginning of this work. As I mentioned in the chat, `~` might be a good choice. We would also use this to concatenate the SD-JWT and SVC when they are sent to the client.

This avoids the overhead that nested JWTs bring, which can be important for QR code and NFC use cases.

**Comment by Sakurann** [comment]
So the options we have now are:
1. concatenating multiple SD-JWTs using `~` + Release
2. including multiple SD-JWTs inside a JWT + Release
3. including SD-JWTs inside a Release

what is the benefit of 2 over 3?

**Comment by Sakurann** [comment]
also, if SD-JWT-R contains multiple `sd_releases`, we need to introduce the mapping which `sd_release` maps to which SD-JWT, a feature provided `presentation_submission` in Presentation Exchange v.2.0. 

I wonder how we draw a line with what is defined in a transport protocol - for example, OpenID4VP mandates using `presentation_submission` for this purpose, so if another mechanism is chosen by SD-JWT, what would implementers do?

**Comment by peppelinux** [comment]
I'd be for including one or more SD-JWTs inside a Release in JWT format, because this create a consolidated presentation with a specific content-type.

the mapping could be made using jti if present in the SD-JWT, anyway even without a mapping an implementation will iterate all the values to find witch matches, 

issuing a jti in SD-JWT would confirm the adoption of a BCP and not a mandatory requirement

**Comment by Sakurann** [comment]
editors want to propose switching to including base64url encoded SD-JWTs in the SD-JWT-Release (vc-data-model approach), from the current approach of passing Release and SD-JWT as separate objects.
this would be extensible to allow multiple SD-JWTs in one Release without going into specifying how to do multiple release
we agree that defying multiple releases itself is out of scop efor sd-jwt but the current approach prevents that altogether because the verifier will receive as many release obejects as sd-jwts and will not know which one's which.

**Comment by Sakurann** [comment]
potentially add a text that this spec defines one way to send an SD-JWT-R, but profiles can define alternative ways (like in VC-DATA-MODEL)

**Comment by Sakurann** [comment]
Combined Format for Presentation is not the only way to do Holder Binding per the text below:

> Other ways of proving Holder Binding MAY be used when supported by the Verifier, e.g., when the Combined Format for Presentation is itself embedded in a signed JWT. See [Section 7](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#enveloping) for details.


So I think making `_sd_jwt` an array would meet the requirement of including multiple SD-JWTs in one JWT (for encryption, holder binding, etc.)

**Comment by bc-pi** [comment]
An application or protocol using SD-JWT can always define some presentation format that allows multiple SD-JWTs. But I'm not sure that defining it in this draft is necessary or appropriate.

**Comment by Sakurann** [comment]
ok, guess vc-data-model already does so with [`verifiableCredential` Property in Verifiable Presentations](https://w3c.github.io/vc-data-model/#presentations-0). I will just do a simple PR clarifying that it is possible.
