### ISSUE TITLE
verifier ignoring holder's keys

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#129]
@tplooker pointed out that verifiers who do not understand `cnf` (or any other claim used to pass holder's key info), verifier will ignore it per JWT's extensibility model. So the attacker takes an issuer-signed item out of a holder-signed item and only sends issuer-signed to the verifier. issuer's signature will pass, and verifier will ignore holder's key info.
JWT's extensibility model backfiring on attacked removing holder binding.

**Comment by danielfett** [comment]
Not exactly sure how the attack works. Whatever is signed by the issuer contains the `cnf` claim (or doesn't). The attacker cannot remove that claim. 

But even if we assume that the  attacker can remove the claim, that would mean that the verifier bases its decision whether to require holder binding or not on information solely defined by the issuer - that is strange, it should be defined by the use case in general. There might also be instances where the issuer let's the user decide whether to include `cnf` (or any other claim for the user key). The verifier must not rely on the presence of that claim.

**Comment by peppelinux** [comment]
I think that the proof of possession in terms of Holder's publick key bounded in the SD-JWT should be defined in the trust framework. The verifier should (or not) prove the possession of the holder.

how this can be achieved?

JWT gives some liberties but cnf is a standard claim and if it's regulated by the rules of a federation the Verifier should verify the cnf value in conformance of the PoP requirement.

if an adversary removes the cnf, the signature validation of the SD-JWT fails.
if the verifier doesn't check the PoP in the way that it has been defined in the technical specs of a trust framework well, it will be banned.

**Comment by danielfett** [comment]
> I think that the proof of possession in terms of Holder's publick key bounded in the SD-JWT should be defined in the trust framework. 

Agree, if the spec is used within a trust framework, the requirement for PoP would probably defined there.

> The verifier should (or not) prove the possession of the holder.

It's the holder proving possession, the verifier checks the proof.

**Comment by peppelinux** [comment]
yes, my english hits again

**Comment by tplooker** [comment]
> Not exactly sure how the attack works. Whatever is signed by the issuer contains the cnf claim (or doesn't). The attacker cannot remove that claim.

Yep you're correct, let me try to explain it a little further

The underlying extensibility model for JWT payloads relies on parties ignoring values they don't understand. Therefore layering in new security related parameters like the `cnf` claim which is optional in the context of general JWTs (e.g un-profiled) which means that a risk does exist that a JWT containing a `cnf` claim could be sent to a verifying party that does not understand it and therefore verifying it as an ordinary JWT without and holder PoP signature present.

**Comment by tplooker** [comment]
I realise this isn't the first/only example of where the general nature of JWT's can mean cross contextual use (e.g cross profile) can lead to these sorts of issues, however it does appear different in the PoP case given that it affects the cryptographic verification process. For instance could it not be plausible that an implementation of SD-JWT only supports the non-holder bound variation?

**Comment by danielfett** [comment]
I added new text during my last review that addresses this topic. Please review!
https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/155/files#diff-40bc3800dd9a7d4411799637caf0b01f82a01242d57264a2e4beb408c3835704R986-R1026

**Comment by Sakurann** [comment]
PR #155
