### ISSUE TITLE
rename SD-JWT-Release to SVC-Release?

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#131]
Some have asked what is "Release"? In short it's a subset of SVC that contains only those claims that the user has consented to share.
maybe SVC -Release is better? (I am also perfectly fine keeping it as is)

**Comment by sbutterfield** [comment]
Should it just be called `Disclosure`?

**Comment by Sakurann** [comment]
I would be ok with `Disclosure` @danielfett ?

**Comment by Sakurann** [comment]
PR #148 
Just Disclosure was confusing with Disclosure Document (renamed from SVC per #134) so chose SD-JWT-Disclosure/SD-JWT-D

**Comment by Sakurann** [comment]
renamed to
> Holder-Selected Disclosures JWT (HS-Disclosures JWT)
:  A JWT created by the Holder that contains the Disclosures from an Issuer-Issued Disclosures Object that the Holder is disclosing to the Verifier. In addition to the Disclosures, it can contain other properties and may be signed by the Holder.
