### ISSUE TITLE
Can we achieve this structure ??

### ISSUE THREAD

**Issue by Muthurajj** [oauth-wg/oauth-selective-disclosure-jwt#142]
{
  "sub": "did:example:ebfeb1f712ebc6f1c276e12ec21",
  "jti": "http://example.edu/credentials/3732",
  "iss": "https://example.com/keys/foo.jwk",
  "nbf": 1541493724,
  "iat": 1541493724,
  "exp": 1573029723,
  "vc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": [
      "VerifiableCredential",
      "UniversityDegreeCredential"
    ]
  },
  "sd_digests": {
    "given_name": "fUMdn88aaoyKTHrvZd6AuLmPraGhPJ0zF5r_JhxCVZs",
    "family_name": "9h5vgv6TpFV6GmnPtugiMLl5tHetHeb5X_2cKHjN7cw",
    "birthdate": "fvLCnDm3r4VSYcBF3pIlXP4ulEoHuHOfG_YmFZEuxpQ"
  }
}

This python code support for VC generation?
Any changes require for achieving this structure?
Pls respond i am  new to python..

**Comment by Sakurann** [comment]
current python code supports only example 1 and not VCs as in example 4

**Comment by Sakurann** [comment]
there are also 3 other implementations in different languages jfyi

**Comment by danielfett** [comment]
We added an example in the document with PR #174 that shows a W3C VC. The example is generated from the python code.
