### ISSUE TITLE
typo in python code after #149

### ISSUE THREAD

**Issue by peppelinux** [oauth-wg/oauth-selective-disclosure-jwt#156]
@Sakurann sorry for the late revision

it seems that here we have merge conflicts exposed
https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/149/files#diff-ce646751295775c4b20fb384cedc0e3374a9c288cc7c93c345f227a422979f46R12

_Originally posted by @peppelinux in https://github.com/oauth-wg/oauth-selective-disclosure-jwt/issues/149#issuecomment-1283809439_

**Comment by danielfett** [comment]
I think this was fixed in a later revision. I don't see it in master.
