### ISSUE TITLE
missing word -01

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#165]
https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-01.html#section-5.8-3 

"For each claim, a JSON literal that decodes to an object with the and the claim value (plus optionally the claim name) is contained in the sd_hs_disclosures object." -> "... decodes to an object with the *salt* and the claim value (plus ..." or something about the salt I think.

**Comment by Sakurann** [comment]
It has been fixed - you can see in the latest editor's version - will be in -02
https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#section-5.8-3
