### ISSUE TITLE
Refactor the spec text and the code to the approach agreed in IETF 115:

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#171]
Refactor the spec text and the code to the approach agreed in IETF 115 described here:
https://docs.google.com/presentation/d/1Hc3xBNN2RL9usCJQKQetrCRk7nYFw6OSLMZPvs1fh_Q/edit?usp=sharing

`+ probably add Justin's suggestion to put hashes in an array as opposed to having them as separate top-level items.

**Comment by danielfett** [comment]
This was done in PR #174 which has been merged.
