### ISSUE TITLE
terminology "Source String hardening"

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#176]
Might be clear enough, or might need alternative suggestion.

https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/174/files#r1028968119

**Comment by danielfett** [comment]
"armoring" is also often used. Let's summon the native speaker to guide us! @bc-pi

**Comment by bc-pi** [comment]
Offhand, I think going back to just "encoding" is probably the way to go in this context.

**Comment by bc-pi** [comment]
On reading it again, "hardening" seems okay too. I feel like "armoring" is mostly used in a different context so don't like that here.

**Comment by Sakurann** [comment]
editors agreed to keep it as-is
