### ISSUE TITLE
SD-JWT with JWS with JSON serialization

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#198]
There are implementations that have a need to use SD-JWT with JWS with JSON serialization.
JWS defines JSON serialization and compact serialization, but JWT does not. 
Would be very helpful in sd-jwt spec defined how to do sd-jwt with JSON serialization.

Example generated by Torsten:

SD-JWT
```
{
       "payload":
       "eyJpc3MiOiAiaHR0cHM6Ly9leGFtcGxlLmNvbS9pc3N1Z
       XIiLCAiaWF0IjogMTUxNjIzOTAyMiwgInR5cGUiOiAiUGVyc29uSWRlbnRpZmljYXRpb
       25EYXRhIiwgImNyZWRlbnRpYWxTdWJqZWN0IjogeyJfc2QiOiBbIi1Bek9ZcEFSbmViN
       VE0UXlESDRhdzJqT3NDdlUtaHZBWUFxS3FpQUlveVEiLCAiLU9vS3ZMS2pvSFVhUEVvQ
       1lzNGM2M1FqTlN5QU9GWEhfNmRPWjdtUjhCUSIsICJCM3gzVE0yNkMxekdOUGpocVNpN
       21acGJiMTNSUEJnS0FEM1NvTEp0ZHhZIiwgIkdYNTg3RnB4Um5uaWJOcjhEcTFJMHhqS
       UN5YmdEYVFkR3EyZGtYeUNheDAiLCAiSnNzR3IzcksyNFQ0bkQyY19XSTVMY0pkSGpoa
       HRjT29KaE9hUkJLTlpHTSIsICJiMWExWmJUcFJYaldVdzJNeEppWHlTaDNIYnZ3SGRSW
       WgyVkRMS09SWXZNIiwgImVOUEZpMmNUZVBHM1ZtOVlNcXNLT3lyMlBzcEZIU2dlNllXW
       GxqUTdlWlkiLCAiamM0SHk0NzEtY1NEcUM1T2dkbWdqYl83Y0dIUURBZGdkcVBGME8ya
       EczUSIsICJ0OHlDYmpTNFVQR1ZkcV9DTEp5U2RSTGVYUm9Gel9aemVvTUM4TjJOX2pjI
       l0sICJhZGRyZXNzIjogeyJfc2QiOiBbIjFpQlV0QWcxdlpmTFFodkE5MloydUFSLTFTV
       3psNjJWRVNGN19xenc3UGsiLCAiSV93WXFkMmJ0TG43cFFQMnhLbnRYTUxENGd0dHlHM
       V9ERFpJUkVtSWtHYyIsICJaNVBSN1RNclQtZXNDUW1KM2w2UXgteXhDT09sVTliZG9TV
       UlhZmxpMVRFIiwgIlpheHZkYlJJRFpwX1ppUlpzSVNXcmZFd0UtOGhkbm9FM2c2WUU3b
       0x5TlEiXX19LCAiZXhwIjogMTUxNjI0NzAyMiwgIl9zZF9hbGciOiAic2hhLTI1NiIsI
       CJjbmYiOiB7Imp3ayI6IHsia3R5IjogIkVDIiwgImNydiI6ICJQLTI1NiIsICJ4IjogI
       lRDQUVSMTladnUzT0hGNGo0VzR2ZlNWb0hJUDFJTGlsRGxzN3ZDZUdlbWMiLCAieSI6I
       CJaeGppV1diWk1RR0hWV0tWUTRoYlNJaXJzVmZ1ZWNDRTZ0NGpUOUYySFpRIn19fQ",
      "protected": "eyJhbGciOiAiRVMyNTYifQ",
      "header": {
        "kid": "e9bc097a-ce51-4036-9562-d2ade882db0d"
      },
      "signature": "mcndQ15m-4FbIzyfBqDeFxfJ-a6F0vgLY1-DzYJHowrhgYyYteVIxHwApv6dNEwYKnegk5
       vg1jxwwYUHU2ZX7g"
}
```
'+ disclosures
```
      "disclosures": [
        [
          "qfUdTVp1zsb019pLaGHrow",
          "given_name",
          "Erika"
        ],
        [
          "cNSnLg5v5T26PxMt3NKj7g",
          "family_name",
          "Mustermann"
        ],
        [
          "J7f73QLAe2nnT4GO2HTWLg",
          "nationalities",
          [
            "DE"
          ]
        ],
        [
          "_cfWMDPMxsRMGHzitGA64A",
          "birth_family_name",
          "Schmidt"
        ],
        [
          "Lnhx-vdNLAwQN2VsPvoqbg",
          "birthdate",
          "1973-01-01"
        ],
        [
          "MGM4tUQu9MtDSOzVxc010g",
          "place_of_birth",
          "Regensburg"
        ],
        [
          "RdEnoePP67aqtaeYhP3kYA",
          "postal_code",
          "12345"
        ],
        [
          "XoINaxEBN_mdeJCUS-PuwQ",
          "locality",
          "Irgendwo"
        ],
        [
          "Wzrr883PdksfkVHwvk90Kg",
          "street_address",
          "Sonnenstrasse 23"
        ],
        [
          "k3Z2k_W6aVfHNb_8P4pIXQ",
          "country_code",
          "DE"
        ],
        [
          "KisX1X1oqftlY2XystVe3g",
          "is_over_18",
          true
        ],
        [
          "MZzvAyDIlAWjDz_7KzZvTQ",
          "is_over_21",
          true
        ],
        [
          "MnF2WogLSlhPoQlBbF-XbQ",
          "is_over_65",
          false
        ]
      ]
    }
```

**Comment by danielfett** [comment]
I agree that this would be useful. The example is not quite right (disclosures should not be decoded), but I can adapt the code to produce JWS with JSON serialization.

**Comment by bc-pi** [comment]
There needs to be some care taken with how this is worded/presented in the SD-JWT document. By definition https://www.rfc-editor.org/rfc/rfc7519#section-1 JWT is only compact serialization. So there is no JWT with JWS JSON serialization and that makes it a little awkward as to how it layers in.  This would be something more like a JWS JSON serialization of a JWT claim set with selective disclosures too.

**Comment by Sakurann** [comment]
this line between JWT and JWS has been driving me crazy recently..
I agree that as long as we say selective disclosure for **JWTs**, we shouldn't put JSON serialization into the main body. so Annex would be the most appropriate probably..

**Comment by bc-pi** [comment]
I think it'd be okay as a separate section in the main document. We'd just need to be a little careful with it.

**Comment by Sakurann** [comment]
example updated. so the question becomes how to pass Disclosures - Brian suggested base64url encoding all of the disclosures as one string as opposed to being tilda separated.

**Comment by bc-pi** [comment]
array of strings

**Comment by bc-pi** [comment]
Mention of both [General JWS JSON Serialization](https://www.rfc-editor.org/rfc/rfc7515#section-7.2.1) and [Flattened JWS JSON Serialization](https://www.rfc-editor.org/rfc/rfc7515#section-7.2.2) is probably needed. Although the `disclosures` array will be the same and at the same level as the `payload`.

**Comment by danielfett** [comment]
Example I created for the IETF116 slides from the partial examples above:

```
{
  "payload": "eyJpc3MiOiAiaHR0cHM6L...Z0NGpUOUYySFpRIn19fQ",
  "protected": "eyJhbGciOiAiRVMyNTYifQ",
  "header": {
    "kid": "e9bc097a-ce51-4036-9562-d2ade882db0d"
  },
  "signature": "mcndQ15m-4FbIzyfB...U2ZX7g",
  "disclosures": [
    "WyJkcVR2WE14UzBHYTNEb2FHbmU5eDBRIiwgInN1YiIsICJqb2huX2RvZV80MiJd",
    "WyIzanFjYjY3ejl3a3MwOHp3aUs3RXlRIiwgImdpdmVuX25hbWUiLCAiSm9obiJd",
    "WyJxUVdtakpsMXMxUjRscWhFTkxScnJ3IiwgImZhbWlseV9uYW1lIiwgIkRvZSJd"
  ]
}
```

**Comment by Sakurann** [comment]
I am not in favor of defining a new disclosures array because it means the Combined Formats for both issuance and presentation will be different depending on the serialization of JWS, which would be an unnecessary complexity when processing. 
Instead, simply saying SD-JWT can be signed as a JSON serialization in addition to compact serialization should be sufficient, because it will allow to keep the same Combined Formats for both issuance and presentation: SD-JWT(can be either serialization)~Disclosures~SD-JWT([opt] in presentation)

**Comment by mickrau** [comment]
Hi, I became aware of this issue through @tlodderstedt when we were talking about combining SD-JWT with JAdES ([TS 119 182-1](https://www.etsi.org/deliver/etsi_ts/119100_119199/11918201/01.01.01_60/ts_11918201v010101p.pdf)). JAdES signatures need JSON Serialization for the most signature levels: B-T, B-LT, B-LTA. 

I agree with @Sakurann and would prefer not to embed the disclosures in the SD-JWT JSON object. My additional argument:
If the disclosures are contained in the same object as the SD-JWT, the user is more likely to forget to extract the disclosures before the presentation, which would result in a full disclosure. The first part of the issuance Combined Format should be passed untouched in the first part of the pressentation Combined Format. 

I have two related questions:
Should the JSON serialized SD-JWT be base64url encoded in the Combined Formats to avoid `~` or other special characters in the SD-JWT part? This would mean:

`base64url(SD-JWT in JSON Serialization)~Disclosures~HolderBindingJWT`

How to distinguish between the two serializations on the holder and verifier side? Do we need two different types?

**Comment by Sakurann** [comment]
> Should the JSON serialized SD-JWT be base64url encoded in the Combined Formats to avoid ~ or other special characters in the SD-JWT part? This would mean: `base64url(SD-JWT in JSON Serialization)~Disclosures~HolderBindingJWT`

yes, SD-JWT in JSON serialization would be b64url encoded in this approach.

> How to distinguish between the two serializations on the holder and verifier side? Do we need two different types?

yeah, I had the same question... I think realistically, based on the trust framework/interoperability profile, holder/verifier will know which serialization to expect. otherwise, holder/verifier needs to check every time after b64url decoding an SD-JWT part for the serialization, based on things like the presence of a JWS header..

**Comment by bc-pi** [comment]
I feel compelled to say that I don't think defining a base64url-encoding of a JWS JSON serialization is at all appropriate for this document.

**Comment by danielfett** [comment]
We chose the tilda-separated format specifically because the compact serialization does not support unsigned values. The JSON serialization does, so I think we should make use of that.

**Comment by awoie** [comment]
If JSON serialisation is added, then I'd suggest changing the name of the spec to SD-JWS. JWT suggests compact serialisation according to the JWT spec.

**Comment by awoie** [comment]
What is the requirement for JSON Serialization in this document? It appears to me that we are talking about a very specific use case that contains specific form of JSON Serialization that should be supported. The reason why I'm asking is because JWS JSON Serialization can sign any arbitrary data (as base64url encoded string). For example, that data can be also a binary image. Having an SD-JWT of a b64url-encoded image would feel a bit awkward to me. I don't think that this is something that we want to achieve. 

I guess what we want is to support signing JSON Objects (e.g., JSON-LD) and encoding the thing as a JWS using JSON Serialization. Having anything other than JSON Objects in the payload would make no sense for the SD-JWT spec.

**Comment by selfissued** [comment]
I agree with @awoie that having anything other than JSON Objects in the payload would make no sense for the SD-JWT spec.

**Comment by mickrau** [comment]
As @awoie said, the discussion here is about the representation of an SD-JWT in JWS JSON Serialization, not about encoding arbitrary payload. Building only on top of JWT with JWS Compact Serialization comes with limitations that not meet the following requirements:

1. unsigned attributes (for e.g. time-stamping the JWS Signature, counter-signature.., see JAdES) 
2. multiple signatures (for e.g. for PQC aware hybrid signatures)

**Comment by alenhorvat** [comment]
> If JSON serialisation is added, then I'd suggest changing the name of the spec to SD-JWS. JWT suggests compact serialisation according to the JWT spec.

This is a very important observation. Current specifications assume that the output of hiding of the claims is JWT that supports only compact serialised JWS, which makes it incompatible with JAdES.

+1 to limit the specification to JSON object + JWS

**Comment by bc-pi** [comment]
> +1 to scope the specification to JSON object + JWS

Note that https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/276/files updated the title to be more inclusive of general JWS with JSON and added some corresponding/explanatory text to the Abstract and Introduction. Which is aiming for that JSON object + JWS scope. For this issue, @danielfett is planning on describing the JWS JSON serialization.

**Comment by alenhorvat** [comment]
Will it still require that JSON object signed with JWS (compact or JSON serialised) contains JWT claims?

**Comment by bc-pi** [comment]
merged PR https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/289
