### ISSUE TITLE
Object Key Name Blinding

### ISSUE THREAD

**Issue by fabian-hk** [oauth-wg/oauth-selective-disclosure-jwt#213]
I have implemented the latest draft of the specification in my [Kotlin](https://github.com/IDunion/SD-JWT-Kotlin) library, and I was thinking, why not also blind object key names? This would have the advantage that no key names are revealed to the verifier, which in turn improves privacy. So a simple credential like this:

```
{
    birthday: "1950-01-01",
    address: {
        street_address: "123 Main St",
        country: "US",
        locality: "Anytown",
        region: "Anystate",
        zip_code: 123456
    },
    nicknames: [
        "A",
        "B"
    ],
    given_name: "Alice",
    family_name: "Wonderland",
    email: "alice@example.com"
}
```

would produce an SD-JWT which also has a digest value for the ``address`` key:

```
{
  "_sd": [
    "igI9yClAfzYXq7aeHSlOXDGiMa_-YtXKV5Efnc4FSqI",
    "CRcudjVh9L518a4k8gYrzMtcP7XAyjeAihr0MTIU9us",
    "sp3HA4QS5o1I1R2DnrBNvhrveG14K2_qXiry3nmKTG4",
    "8nlxltqpUUGYffQKXYvaamZQPrvGrFJHRob5UGTIaco",
    "zm2ur1QxWqgA_v6fzE7y6iRpVMQoikJqf-FTyWnBoRg",
    "td4nlcMY_ltwYAHZqSHViqjrDha1muPsJwJ3aY7QA4s",
    "mELeKWyBm_RgNGzOgCxQwqbaNkAH0CKi3UsigqaBtqo"
  ],
  "_sd_alg": "sha-256",
  "iss": "http://issuer.example.com",
  "exp": 1676656291,
  "iat": 1676569891,
  "IYUO3yeyrLcnUq71btorYfUMi2K-MJVLnmylG5qbqQI": {
    "_sd": [
      "_Dyl_b2TEeBU92z3X_pDLYBgU2ymDFl-c_BWYCvTN4w",
      "9k13ilEUn0jJvKw5h8aYiDHPJJ2-P1Ze5tSl0Yr8xEM",
      "1qIjSVkHME5KW0BuSIvtt2BaZruheu371V3Pb9HxU8U",
      "uQ9oX166S0fELlFKBMjO1jS8VoAvOtcEVway3WlLxEQ",
      "fREXtv8ZbeP3OxOwWYC4-snC3xbpjjJQv9ti6NIyLGM",
      "JNwla2uNQakFuiusGTpY-LDKUnzLhOUeqIRayimzprE",
      "mu9z7FTxYoQzY_uu6sM1r4mqBqEXIM6ioRDNcAup_uA"
    ]
  }
}
```

In order to recreate the original credential, we would need an additional disclosure, which would look something like this:

```
WyJyckRKdGNOVzFpcUFYWEdTdl9qWUtBIiwiYWRkcmVzcyJd

# Decoded
[
    "rrDJtcNW1iqAXXGSv_jYKA",
    "address"
]
```

There is of course an additional complexity in implementing this, but it is quite simple. I have implemented it in the [feature/object-key-blinding](https://github.com/IDunion/SD-JWT-Kotlin/tree/feature/object-key-blinding) branch of my Kotlin library.

**Comment by bc-pi** [comment]
There also some additional complexity that maybe isn't obvious at first. The entities would have to deal with and reason about the additional optionality. For example, a holder would need to know to disclose the name whenever disclosing a subordinate so would have to keep track of a lot more in terms of the Disclosures and the relationship between some of them. A verifier would need to deal with disclosed claims under an undisclosed name. The approach would need to say whether clear text claims would be allowed under a blinded name/key. And there too, what would it mean to a verifier to get claims where a key name is blinded but has clear data under it. 

Also I'm not sure it's acceptable to use the digest value directly as the key value. Thus far we've tried to clearly differentiate the blinded parts with the "_sd" array claim. And in other design discussions we've avoided use of the hash value directly in place of where the actual value would be. 

On one level it is quite simple. But it's deceptively so. I'm not sure it warrants the additional complexity.

**Comment by bc-pi** [comment]
There is some relation to #194 that's probably worth considering.

**Comment by fabian-hk** [comment]
Looking at #194, we could prefix the blinded key names with ``_sd:`` to make it clear that this is a digest and the verifier must look for a disclosure. I do not think it makes much sense to disclose plaintext claims under an undisclosed key. For example, it would make it impossible to create a type-safe class from the credential in my Kotlin library. So I would suggest that a verifier should not process the key if it cannot find the plaintext value.

**Comment by danielfett** [comment]
We talked about this in our editor's meeting and think that it might be preferable to instead allow recursive SD-JWTs - i.e., digests may contain objects with _sd keys.

**Comment by bc-pi** [comment]
"i.e., digests may contain objects with _sd keys." -> I *think* you mean digests can point to Disclosures that may contain objects with _sd keys.

**Comment by bc-pi** [comment]
PR #220 was merged
