### ISSUE TITLE
Tooling: Dump header, allow header modification

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-selective-disclosure-jwt#215]
Got external feedback:

* The tooling should allow custom values in the header
* We currently have no way to show the headers

**Comment by Sakurann** [comment]
more relevant to externalized reference implementation repo now. header to HB JWT is introduced in this PR: https://github.com/danielfett/sd-jwt/pull/3

**Comment by bc-pi** [comment]
this issue really now applies to the python reference implementation that is used to generate the examples https://github.com/danielfett/sd-jwt

**Comment by bc-pi** [comment]
created a new issue in reference implementation to track this https://github.com/danielfett/sd-jwt/issues/12
