### ISSUE TITLE
type of salt in disclosures

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauth-wg/oauth-selective-disclosure-jwt#218]
The current snapshot of the SD-JWT specification allows the type of salt in disclosures to be any type allowed in JSON (e.g. number) although the specification recommends a base64url-encoded string.

After finishing implementing a small Java library for SD-JWT, I now feel that such flexibility does not bring much benefit and instead brings problems such as incompatibility and complexity in implementations.

I think that the specification should require the type of salt be always a base64url-encoded string.

**Comment by bc-pi** [comment]
I tend to agree that having salt always be a string would be sufficient and more straightforward. I don't see any real benefit in allowing any type, actually. But I think @danielfett is the originator of that text so maybe he can explain the rational? If there's not a good reason (that I'm missing) to allow for the flexibility, however, I'd suggest we make salt always be a string.

**Comment by danielfett** [comment]
The reason for "any type" is that *ideally*, nobody needs to handle this element, as it just sits there introducing randomness. Nobody needs to read it, process it, decode it, etc.. 

But I tend to think from a Python world where "any type" is a thing. Of course, in other languages and frameworks (especially JSON libraries), this may introduce complexity and having a fixed type would be useful. And I guess there's no real downside to that. So I would be open to changing this to a string.

**Comment by bc-pi** [comment]
Totally agree with the idea that ideally, nobody needs to handle the element, as it just sits there introducing randomness and will be discarded. But there are JSON frameworks that want to be helpful by doing all sorts of data type binding. Which can be super helpful in general but can make dealing with "any type" somewhat cumbersome.

**Comment by Sakurann** [comment]
PR merged
