### ISSUE TITLE
default hash algorithm

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauth-wg/oauth-selective-disclosure-jwt#219]
If the SD-JWT specification specifies `sha-256` as the default hash algorithm, the `_sd_alg` claim can be omitted and implementations can be a little simpler and more interoperable.

**Comment by bc-pi** [comment]
I'd suggested this somewhat in passing as part of #169. But it kinda got lost in the noise of that one. I still think it's worthwhile, however. Unless my esteemed  co-editors have strong/good objections, I'd like to make this change.

**Comment by danielfett** [comment]
Works for me!

**Comment by danielfett** [comment]
Please adapt the implementation as well or make assign this issue to me so that I remember to do that.

I suspect that only these lines need to be adapted for verification:


        if DIGEST_ALG_KEY not in self._sd_jwt_payload:
            raise ValueError("Missing hash algorithm")

**Comment by bc-pi** [comment]
#222 was merged
