### ISSUE TITLE
Java Library for SD-JWT (com.authlete:sd-jwt)

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauth-wg/oauth-selective-disclosure-jwt#223]
I published an open-source Java library for SD-JWT at https://github.com/authlete/sd-jwt. It would be appreciated if the library is added in the README.md file of this repository.

**Comment by Sakurann** [comment]
Thank you!! That's awesome!! will do a PR

**Comment by bc-pi** [comment]
PR #227 merged
