### ISSUE TITLE
Is there a better way to format Disclosures in the examples?

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#231]
Below is how Disclosures are currently formatted in the examples. Maybe only me, but I think it might be more readable if there were indentations or bulletpoints...

> **Disclosure for is_over_65:**
> 
> WyI0RDd2N1JWTTh2THUwN0tRVUJqOF9RIiwgImlzX292ZXJfNjUiLCB0cnVlXQ
> 
> Contents:
> 
> ["4D7v7RVM8vLu07KQUBj8_Q", "is_over_65", true]
> 
> SHA-256 Hash: 8Bcr2ZGImJ9FlsBNmGiLgj7XmHm-g8QOuYVSXOWoM58

Maybe something like:

> Claim `is_over_65`:
> - Disclosure: WyI0RDd2N1JWTTh2THUwN0tRVUJqOF9RIiwgImlzX292ZXJfNjUiLCB0cnVlXQ
> - Contents: ["4D7v7RVM8vLu07KQUBj8_Q", "is_over_65", true]
> - SHA-256 Hash: 8Bcr2ZGImJ9FlsBNmGiLgj7XmHm-g8QOuYVSXOWoM58

**Comment by danielfett** [comment]
I did consider that, but there were some problems regarding the length of the lines in the legacy text format. But I can give this another try.

**Comment by danielfett** [comment]
New attempt to fix this in #252.
