### ISSUE TITLE
Considering registering a media type that can be used as `typ` for SD-JWT-VC

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#236]
`vc+sd-jwt` is being suggested per issue-comment [here](https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/232#discussion_r1133083641)

related to issue #74 and PR #229.

**Comment by bc-pi** [comment]
I wasn't there but myy understanding of the outcome of discussions at IETF116 is that the sd-jwt spec should to register general +sd-jwt, and application/sd-jwt.

**Comment by bc-pi** [comment]
PR #249 merged
