### ISSUE TITLE
Example 2 mismatch

### ISSUE THREAD

**Issue by christianpaquin** [oauth-wg/oauth-selective-disclosure-jwt#240]
[Example 2b](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#name-example-2b-adding-decoys) states that it was created using data from [Example 2a](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#name-example-2a-handling-structu), but adding decoy values. I'd expect its `_sd` param to be a superset of example 2a's, but it's not the case. Am I missing something?

**Comment by danielfett** [comment]
Example 2b includes different nonces than Example 2a.

We try to use deterministic random numbers to generate the examples, but in this case, due to the order in which the decoys and regular salts are created, this approach does not produce the same nonces for the same "real" disclosures.

**Comment by bc-pi** [comment]
PR was merged
