### ISSUE TITLE
Add public keys to examples

### ISSUE THREAD

**Issue by christianpaquin** [oauth-wg/oauth-selective-disclosure-jwt#241]
It would be useful to publish the issuer's public key used to generate the examples. This would allow implementations for validate the JWS from the spec.

**Comment by danielfett** [comment]
The key pairs can be found here: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/blob/master/sd_jwt/demo_settings.py

However, there is the idea of exposing all data (keys, examples, outputs of reference implementation, etc.) in a more accessible way to allow cross-library testing. I have not worked on that yet, but it's on my list.

**Comment by bc-pi** [comment]
take the public key from settings.yml and put it in JWK format with some text saying it can be used to verify the examples

**Comment by bc-pi** [comment]
PR https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/296 was merged
