### ISSUE TITLE
use of decoys results in rejection by the holder as well as the verifier

### ISSUE THREAD

**Issue by panva** [oauth-wg/oauth-selective-disclosure-jwt#242]
When decoys are used (_sd members not corresponding to a disclosure are added) the [Processing by the Holder](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-03#section-6.1-2.3) says to

> If any of the digests cannot be found, the Holder MUST reject the SD-JWT.

I imagine this is not intended and the holder should ignore missing disclosures instead?

Same in [Verification by the Verifier](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-03#section-6.2-4.5.2.2.2.2.2.1)

> Find the Disclosure referenced by the digests. If no such Disclosure can be found, the Verifier MUST reject the presentation.

**Comment by danielfett** [comment]
**Processing by the Holder:**
> > If any of the digests cannot be found, the Holder MUST reject the SD-JWT.

This seems fine to me. In the context, "the digests" refers to "the digests of the Disclosures". If there is a Disclosure that hashes to a digest not found in any _sd array, the SD-JWT is invalid.
 
Maybe we can clarify by modifying this to:

> If there is a digest of a Disclosure that cannot be found, the Holder MUST reject the SD-JWT.

**Verification by the Verifier:**

> > Find the Disclosure referenced by the digests. If no such Disclosure can be found, the Verifier MUST reject the presentation.

This is wrong and should read "If no such Disclosure can be found, the digests MUST be ignored."

Thanks for bringing this up, Filip!

**Comment by danielfett** [comment]
That would force the Holder to act correctly, but would it provide any benefit beyond that?

**Comment by danielfett** [comment]
The changes above are included in PR #245 - please review @panva @c2bo

**Comment by Sakurann** [comment]
PR merged
