### ISSUE TITLE
not to do anything with the content of a Disclosure until/unless it's digest value is found 

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#248]
Do we need implementation consideration "to suggests not to do anything with the content of a Disclosure until/unless it's digest value is found in an _sd element." maybe it is already clear.

**Comment by bc-pi** [comment]
I think it's clear enough as it is. That was just a note in the PR about why I thought a particular verification step was in the appropriate place.  I don't think it needs an implementation consideration or anything more.
