### ISSUE TITLE
rename `combined format for presentation/issuance` terms?

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#254]
I find myself using `combined format for presentation/issuance` to refer to the entire `series of base64url-encoded values`, which is not exactly accurate..? would it make sense to rename to something like `combined issuance/presentation values"?

**Comment by bc-pi** [comment]
Let's talk about naming on a call soon. There does seem to be some opportunity for improvement (I'm not sure I use the terms right!). You'd also shared some notes from IETF 116 that had similar sentiment, "suggestion to rename combined formats to SD-JWT issuance and SD-JWT presentation? Torsten feedback: many people are confused that SD-JWT means combined formats and not just a JWT."

**Comment by danielfett** [comment]
But the combined format for presentation *is* the series of base64url-encoded values?

Anyway, I think it should be just (SD-JWT) Presentation and (SD-JWT) Issuance.

I usually use the terms as follows:

 * SD-JWT - just the JWT (i.e., the first part of the Presentation/Issuance)
 * (SD-JWT) Presentation: what we currently call Combined Format for Presentation
 * (SD-JWT) Issuance: what we currently call Combined Format for Issuance

IIRC what Torsten referred to was that the whole Combined Format (for I./P.) should be called SD-JWT. I think we should not go down that road.

**Comment by Sakurann** [comment]
> But the combined format for presentation is the series of base64url-encoded values?

it is not intuitive to be call "values", a "format"...

> I generally agree with @danielfett above but do admit to using the term SD-JWT generically to mean any or all of those three. I doubt I'm alone in that.

you are not.. I generally use `SD-JWT` to mean SD-JWT with disclosures and `issuer-signed SD-JWT` to point only to JWS.

I would rather not change the terms again, but I do see people struggle with using the terms "combined formats for issuance/presentation". maybe it should simply be something like "SD-JWT for issuance" and "SD-JWT for presentation"...

**Comment by awoie** [comment]
Combined format for presentation might cover both use cases. It is also fine to see the data object that travels from the issuer to the holder as a combined format for presentation (without HB).

**Comment by TakahikoKawasaki** [comment]
One idea.

| old name | new name | new short name |
|:--|:--|:--|
| SD-JWT | SD-JWT | |
| Combined Format | SD-JWT Package | |
| Combined Format for Issuance | SD-JWT Package for Issuance<br>or SD-JWT Issuance Package | SD-JWT Issuance |
| Combined Format for Presentation | SD-JWT Package for Presentation<br>or SD-JWT Presentation Package | SD-JWT Presentation |

**Comment by awoie** [comment]
Can we call it "presentation object" or "presentation envelope" or "presentation container", "issuance object" or "issuance envelope" or "issuance container". When referred to in other specs, it would be much easier to read.

**Comment by Sakurann** [comment]
Editors are leaning towards `SD-JWT Issuance format` and `SD-JWT Presentation format`. and short names will establish themselves :)

**Comment by Sakurann** [comment]
> I think it might not be even necessary to distinguish these two in the specification and just merge both sections together.

good point. editors are leaning towards having one section "SD-JWT Issuance/Presentation format" where the Issuance format is `<SD-JWT>~<Disclosure>...<Disclosure>~`, so same as Presentation format without HB JWT.

**Comment by bc-pi** [comment]
>good point. editors are leaning towards having one section "SD-JWT Issuance/Presentation format" where the Issuance format is <SD-JWT>~<Disclosure>...<Disclosure>~, so same as Presentation format without HB JWT. 

I'd suggest just calling the whole structure SD-JWT then...

**Comment by danielfett** [comment]
Let's do that.

**Comment by Sakurann** [comment]
"Issuer issues SD-JWT and verifier presents sd-jwt"
ie no explicit term for the issuer-signed JWS
needs to PRs, adding `~` to issued SD-JWT and changing terminology.

**Comment by bc-pi** [comment]
The terms "Combined Format for Issuance" and "Combined Format for Presentation'' go away and the whole structure, issued or presented, can be called an SD-JWT. To align the two formats, the last Disclosure will always be followed by a ~ (tilde) character (currently the Combined Format for Issuance does not have the trailing tilde). When key binding is required for presentation, a key binding JWT will be appended to the end of the whole thing after the trailing tilde.
