### ISSUE TITLE
decoy digest sections duplication

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#255]
both sections 9.3 and 5.1.1.3 talk about decoy digests and they are overlapping in content - would be good to consolidate.

**Comment by bc-pi** [comment]
Looking again at [5.1.1.3](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#section-5.1.1.3) and [9.3](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#section-9.3) - I don't see need to consolidate.

**Comment by Sakurann** [comment]
ok!
