### ISSUE TITLE
 A.1.: explanatory text doesn't match example content

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#256]
The text in [A.1. ](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#appendix-A.1)[Example 2a: Handling Structured Claims](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#name-example-2a-handling-structu) doesn't line up with the example content. Looks like this https://github.com/oauth-wg/oauth-selective-disclosure-jwt/commit/a94e2d1a2c4306a45e7d4a42df482d3fa19a9972#diff-419b00ae17c9bf1fc5862b7cb23eb2c0b44423b8422ccda8fcf4df73b7cef7a6 change took the text and content out of sync.  Text like "a structured object for the address claim, allowing for separate disclosure of the individual members of the claim" and "discloses only region and country of the address property" doesn't match with the example content that has the whole address claim selectively disclosable.

**Comment by bc-pi** [comment]
I could (probably) fix this but am unsure if there was intent behind that change...

**Comment by danielfett** [comment]
That was most likely accidental as I had to touch all examples for that change and probably got confused in between :-)

**Comment by bc-pi** [comment]
merged PR #257 which is only touching examples/simple_structured.yml but should eventually get incorporated with merging of some other PRs around the examples like #252 and #251
