### ISSUE TITLE
add a note that Quantum resistant algs could be used with sd-jwt

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#261]
based on the feedback during the IIW session

**Comment by OR13** [comment]
If these make it through, they would all work for sd-jwt.

- [draft-ietf-cose-dilithium](https://datatracker.ietf.org/doc/draft-ietf-cose-dilithium/)
- [draft-ietf-cose-falcon](https://datatracker.ietf.org/doc/draft-ietf-cose-falcon/)
- [draft-ietf-cose-sphincs-plus](https://datatracker.ietf.org/doc/draft-ietf-cose-sphincs-plus/)

I would not add a direct pointer to any of them, but perhaps a direct pointer to "signature algorithms" in 

https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms

would work.

**Comment by bc-pi** [comment]
Add something like "... for the security of the SD-JWT depends on the security of the signature algorithm. Any of the defined JWS algorithms can be used including future PQ stuff" to [8.1](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#section-8.1).  [Mandatory signing of the SD-JWT](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#name-mandatory-signing-of-the-sd)
