### ISSUE TITLE
rename specification to SD-JWS

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#265]
We are adding JSON serialization which is prohibited by JWT, but allowed by JWS
(cc @awoie @paulbastian)

**Comment by selfissued** [comment]
I would not change the name. Even once a JSON Serialization is added, SD-JWTs are more like JWTs than JWSs. We are using a JSON payload. We are using JWT claims. We are not signing arbitrary binary data.

Also, brands matter - they matter a lot! We have a recognized brand used by other people and other specs. Let's not throw away the value of that name recognition. 

Finally,  SD-JWT is easier to say than SD-JWS!

**Comment by danielfett** [comment]
strong +1 to all of what Mike said!

Also, JWT will still be the main format in terms of how everything is presented in the spec.

**Comment by bc-pi** [comment]
also strong +1 to *not* changing the name

**Comment by paulbastian** [comment]
I might agree with Michaels points. I didn't know yet that JWT limits JWS to json payload. I would vote to keep the name therefore to SD-JWT but consider adding the json serialization to it anyway as it allows the support for JAdES and more better possibilities for multi signature having PQC in mind

**Comment by Sakurann** [comment]
> We are using a JSON payload. We are using JWT claims.

this is not true. we are allowing JSON-LD (which is still JSON, yes), but we are not mandating the use of JWT claims. SD-JWT does not care about the paylaod beyond _sd and _sd_alg. 

I do not understand "Even when JSON Serialization is added, SD-JWTs are more like JWTs than JWSs. "

**Comment by Sakurann** [comment]
> Also, JWT will still be the main format in terms of how everything is presented in the spec.

what does that mean? SD-JWT does not require the payload to be a JWT

**Comment by Sakurann** [comment]
Nothing in RFC7515 (JWS) mandates what is signed by JWS to be a JWT, I think SD-JWT should do the same.

**Comment by Sakurann** [comment]
> Also, JWT will still be the main format in terms of how everything is presented in the spec.
Yes, It's same in JWS RFC, but the name is still JWS :)

**Comment by danielfett** [comment]
I would have no problem with clarifying this in the long-form title, but keeping SD-JWT as the short form. Something like this:

> SD-JWT: Selective Disclosure for JSON Web Tokens and JWS

**Comment by danielfett** [comment]
Or maybe: 

> Selective Disclosure for JSON Web Tokens (SD-JWT) and JWS with JSON payloads

**Comment by Sakurann** [comment]
Solely for branding purposes, I think it should stay as "SD-JWT" for short name.
as long as editors agree "it is more general than JWT, specialized form of JWS", and that is reflected, I am satisfied.

**Comment by bc-pi** [comment]
> I would actually prefer this:
>
> >    SD-JWT: Selective Disclosure for JSON Web Tokens and JWS with JSON payloads


Probably shouldn't mix long (JSON Web Tokens) and short (JWS) in the title so maybe: 

> SD-JWT: Selective Disclosure for JWT and JWS with JSON payloads

**Comment by bc-pi** [comment]
PR #276 updates the title to be more inclusive of general JWS with JSON and added some corresponding/explanatory text to the Abstract and Introduction. I'm not convinced this is the right thing to do or that PR is the right way to do it. But it's there as something concrete to discuss.

**Comment by Sakurann** [comment]
PR #276 merged
