### ISSUE TITLE
Verifying the claim value

### ISSUE THREAD

**Issue by yaronf** [oauth-wg/oauth-selective-disclosure-jwt#268]
In the section [Verification by the Verifier](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#name-verification-by-the-verifie), we should require that the Verifier should check that each claim's value is valid JSON. This should probably be after step 4.3.2.2. If weird claim values are accepted, e.g. `["bla",` (no closing bracket) we'd be open to interesting injection attacks.

**Comment by danielfett** [comment]
Maybe we need to clarify, but step 4.3.2.2. is intended to capture this already:

> If the Disclosure is not a JSON-encoded array of three elements, the Verifier MUST reject the Presentation.

We may want to change this to

> If the Disclosure is not valid JSON or is not a JSON-encoded array of three elements, the Verifier MUST reject the Presentation.

**Comment by yaronf** [comment]
Sorry if I wasn't clear. Here's an example:
```
["F3s1PCF9KwzIDiKJj6kzJQ", "names", "[\"john\", \"jill\"]"]
```
is a valid disclosure with a valid claim value (an array with 2 string elements), but
```
["F3s1PCF9KwzIDiKJj6kzJQ", "names", "[\"john\", \"jill\""]
```
has an invalid claim value because there's no closing bracket.

In other words, we need to validate the disclosure but also the claim value inside it.

**Comment by danielfett** [comment]
From the point of SD-JWT, the claim value that is disclosed in your example is a string with the content `[\"john\", \"jill\"]` (or `[\"john\", \"jill\"` in the second example). The contents of the string may or may not be JSON, and it most cases it will not be JSON. SD-JWT does not make any assumptions on the contents.

So from the point of SD-JWT, both your examples are perfectly fine claims with the name `name` and a string value that just happens to look like JSON.

I would however expect that a claim called `names` would use a JSON array instead (see [this example](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#appendix-A.3-55) in the spec):

    ["F3s1PCF9KwzIDiKJj6kzJQ", "names", ["john", "jill"]]

This would be covered by the current wording (and more clearly by the proposed new wording).

**Comment by yaronf** [comment]
You are totally right, sorry. It would be nice if there were some examples with claims that are integers or booleans, to demonstrate this point.

**Comment by Sakurann** [comment]
PR #292 merged
