### ISSUE TITLE
Typo in 8.2?

### ISSUE THREAD

**Issue by yaronf** [oauth-wg/oauth-selective-disclosure-jwt#269]
I think the first paragraph mixes Issuer with Verifier.

Old:
> Holders can manipulate the Disclosures by changing the values of the claims before sending them to the Issuer. The Issuer MUST check the Disclosures to ensure that the values of the claims are correct, i.e., the digests of the Disclosures are actually present in the signed SD-JWT.

New:
> Holders can manipulate the Disclosures by changing the values of the claims before sending them to the Verifier. The Verifier MUST check the Disclosures to ensure that the values of the claims are correct, i.e., the digests of the Disclosures are actually present in the signed SD-JWT.

**Comment by bc-pi** [comment]
Thanks for catching that. We'll fix.
