### ISSUE TITLE
SD-JWT VC example 

### ISSUE THREAD

**Issue by tlodderstedt** [oauth-wg/oauth-selective-disclosure-jwt#272]
I suggest to align the example https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#name-example-4a-w3c-verifiable-c with the design specified in https://github.com/vcstuff/draft-terbu-sd-jwt-vc. The obvious difference is the use (or omission) of ’credentialSubject‘.

**Comment by Sakurann** [comment]
PR merged

**Comment by bc-pi** [comment]
merged pf
