### ISSUE TITLE
Guidance on what to do when encountering an invalid _sd value

### ISSUE THREAD

**Issue by tplooker** [oauth-wg/oauth-selective-disclosure-jwt#278]
Its clear from the draft the expected format of the `_sd` member in an SD-JWT, however the processing behaviour for verifying parties when this is incorrect is unclear, e.g should a verifier error, or ignore in the following cases.

1. Where the value of an `_sd` claim is not an array, instead some other permitted JSON type.
2. Where the value of an `_sd` claim is an array, but polymorphic e.g containing elements that are not strings as expected.

I would assume a verifier should fail in either case?

**Comment by danielfett** [comment]
I think 1 is covered by this:

> Find all _sd keys in the SD-JWT payload. For each such key perform the following steps (*): 
>   * If the key does not refer to an array, the Verifier MUST reject the Presentation.

2 is not explicitly covered yet, but should be.

**Comment by bc-pi** [comment]
this will be done with PR #283

**Comment by Sakurann** [comment]
PR merged.
