### ISSUE TITLE
Guidance on what to do when a disclosure presented does not match to a digest element in JWT

### ISSUE THREAD

**Issue by tplooker** [oauth-wg/oauth-selective-disclosure-jwt#280]
There is language in the specification which defines behaviour (to error) when encountering duplicate usages of a single disclosure, but I couldn't find any guidance on what to do if a supplied disclosure does not match to any digest in the JWT.

Suggested behaviour here would be to error, but is that too strict?

**Comment by danielfett** [comment]
For the holder, the [current text](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#section-6.1) specifies:

> If there is a Disclosure with a digest that cannot be found in any _sd array, the SD-JWT is invalid and the Holder MUST reject the SD-JWT.

For the Verifier, we say

> Verifiers MUST ensure that (...) the SD-JWT is valid, i.e., it is signed by the Issuer and the signature is valid, all Disclosures are correct, i.e., their digests are referenced in the SD-JWT or in other Disclosures referenced in the SD-JWT (...)

This is however not currently reflected in the Algorithm provided in Section 6.2. We might want to add that after this step:

> If any digests were found more than once in the previous step, the Verifier MUST reject the Presentation.

**Comment by danielfett** [comment]
See also Issue #244 where we concluded the we don't need such a check. In any case we need to resolve the disconnect between the requirements on the Verifier and the actual algorithm as shown in my previous comment.

**Comment by tplooker** [comment]
Understood, it would appear the consensus is not to be so strict then? E.g a verifier processing an SD-JWT that contains a digest that is un-used should just ignore it?

**Comment by bc-pi** [comment]
> E.g a verifier processing an SD-JWT that contains a digest that is un-used should just ignore it?

Yes, digests that are unused have to be ignored. The whole selective disclosure mechanism relies on that - any decoy digest or Disclosure that the holder doesn't release will have a digest in the SD-JWT payload or referenced disclosures that is unused (meaning that it doesn't reference a Disclosure that exists from the verifiers perspective).

I think this comment thread was mostly about how to treat unreferenced Disclosures though. Current text has the holder reject.  For the verifier it's maybe a bit ambiguous now with the text Daniel quoted above while no mention in the actual verification algorithm steps. #244 did result in thinking it was not needed. But I think it'd be good to treat unreferenced Disclosures the same for both Holder and Verifier as it might make code paths for general checking the whole SD-JWT more reusable.  And honestly either reject or ignore would seem okay.

**Comment by tplooker** [comment]
Right yes sorry I should have been clearer in my latest comment that I was actually meaning to talk about unreferenced disclosures. I agree it should be the same for both issued and presented forms of SD-JWTs too. What I would add though is I dont really see much of a downside in doing this check though given it might reduce some risk. For example implementations already need to track during the substitution phase that a disclosure isn't substitute twice right? So it wouldn't be that complex to just say for all the disclosures substituted make sure it matches the set you started with.

**Comment by bc-pi** [comment]
Discussion offline and plan is to better align/combine the verification steps and then have additional steps as need for holder and verifier.

**Comment by bc-pi** [comment]
#294 has been merged so now the relevent verification steps are consolidated for holders and verifiers
