### ISSUE TITLE
Improve Structure, especially around Example 1

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-selective-disclosure-jwt#290]
_Originally posted by @Sakurann in https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/283#discussion_r1227387227_

>               I don't disagree this section probably belongs here in terms of the order, but the level of this section feels off (looked at [the rendered ver of this branch](https://drafts.oauth.net/oauth-selective-disclosure-jwt/danielfett/arrays/draft-ietf-oauth-selective-disclosure-jwt.html#name-format-of-an-sd-jwt)).
> 
> I think there is a logical separations between sections from 5.1 to 5.5 (basic operations) and from sections 5.6 to 5.7 (advanced concepts) from 5.8 to 5.9 (content of the SD-JWT) and 5.10 to 5.11 (combined formats). and having them all at the same level makes it hard to read..

I agree. There will be other changes coming to the presentation/issuance format sections and a new section for the JWS JSON Serialization. After these changes, we should revisit the current structure and modify as needed.

**Comment by Sakurann** [comment]
@rohan-wire, were you planning to do a PR that could partially address this?

**Comment by Sakurann** [comment]
PR merged
