### ISSUE TITLE
two dots as &#168 display issue 

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#299]
"it shows as `two dots &#168; placed over the letter` is there any way to change that..? (this is not the change introduced in this PR)" on the text in the doc at https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#section-5.1.1.1-9.1 "A different way to encode the umlaut (two dots &#168; placed over the letter):"

_Originally posted by @Sakurann in https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/293#discussion_r1234687656_

**Comment by danielfett** [comment]
Not sure why this broke now. I created a PR because the example wasn't ideal anyway: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/300

**Comment by danielfett** [comment]
I just noticed that the PR does not fully solve the problem. We have the same problem somewhere else as well: 

![Screenshot_20230620_211135](https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/89476/36ffd67f-9014-4c69-9d7b-fc5d8e5dd3d7)

**Comment by bc-pi** [comment]
it's seems to have been an issue at least back to -01 https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-01.html#section-5.1-9 and/or -02 https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-02.html#section-5.2.1.1-9.1 

I'm sure we could fight with the tool chain to fix it. But at what cost? I'm inclined to just reword that "The two representations... " part to make the issue go away.

**Comment by Sakurann** [comment]
PR merged
