### ISSUE TITLE
JWT claims IANA registration requests

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#315]
This [TBD](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-05.html#section-12-1) was meant as a placeholder/reminder for JWT Claims Registration requests to IANA that would be needed eventually.   

 The `_sd` and `_sd_alg` claims should be registered. 

I'm not sure about `...` to be honest, which is ironic b/c I'm supposed to know about such things (see the so-called experts [listed in the registry](https://www.iana.org/assignments/jwt/jwt.xhtml#claims)). But it's somewhat different than the other claims in the registry. But, I dunno, requesting registration is probably the way to go w/ `...`.

**Comment by Sakurann** [comment]
I share your unsureness, and agree that requesting registration is the way to go.
btw in the spec, we have a text registered `...` claim, so if we decide not to register it, that text needs to be updated.

**Comment by bc-pi** [comment]
> btw in the spec, we have a text registered `...` claim

Wait... really, where?

**Comment by danielfett** [comment]
PR has been merged.
