### ISSUE TITLE
terminology: JWT payload, JWT body, JWS payload

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#319]
feedback received:

---

The draft uses the terms "JWT body" and "JWT payload" which are not used / not defined in RFC 7519.
While it is quite clear from the context what is meant, it could be preferable to use the term (JWT Claims Set) defined in RFC 7519 in order to avoid any misinterpretations.

**Comment by Sakurann** [comment]
it is true that https://www.rfc-editor.org/rfc/rfc7515#section-2 only defines JWS payload. JWT payload is mainly used as "SD-JWT payload", which I think it fine, but JWT body might be worth revisiting..

**Comment by bc-pi** [comment]
FWIW [DPoP](https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-16.html), which is past last calls and IESG reviews and in the RFC editor queue, uses "JWT payload".

**Comment by alenhorvat** [comment]
Similar with "issuer signed JWT" appears quite frequently in the text, even though some JWS signatures don't use JWT claims.

**Comment by Sakurann** [comment]
PR merged
