### ISSUE TITLE
Disclosing claims from different credentials

### ISSUE THREAD

**Issue by alenhorvat** [oauth-wg/oauth-selective-disclosure-jwt#322]
Does the specification support disclosing claims from different credentials?

The text doesn't seem to cover the scenario (maybe I missed it);

I guess option is:
- create multiple SD-JWTs, sign each of them and send it as array?

**Comment by danielfett** [comment]
The option to handle multiple credentials was considered (there are a couple of closed issues on this, e.g., https://github.com/oauth-wg/oauth-selective-disclosure-jwt/issues/114), but ultimately considered out of scope for the reasons discussed there. Presenting multiple credentials is left to the transport protocol.

**Comment by alenhorvat** [comment]
Can the text in section 7 be improved?
_For such use cases, the SD-JWT SHOULD be transported as a single string_

If sd-jwt is signed using JSON serialised JWS sd-jwt won't be a string but a JSON object.

Should this also be mentioned in the holder binding section? E.g., when claims from multiple credentials are shared each of them need holder binding, etc. and the rest is left to the protocol?

Holder binding, currently, already assumes something about the protocol (nonce).
