### ISSUE TITLE
Change how VC formats are described

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-selective-disclosure-jwt#341]
In the appendix, we should avoid suggesting that we're describing an SD-JWT VC and refer to the now-adopted SD-JWT VC spec instead.

**Comment by danielfett** [comment]
The same applies to our W3C VC Example - we should be very explicit that we're not defining anything here and just giving examples.

**Comment by Sakurann** [comment]
these clarifications would be nice.

**Comment by bc-pi** [comment]
I'm sure you are aware but the draft-terbu-sd-jwt-vc reference needs to be updated to draft-ietf-oauth-sd-jwt-vc.

**Comment by Sakurann** [comment]
Actually, the current text reads ok to me? what would you change..?

> In this example, the artifacts defined in this specification are used to represent SD-JWT-based Verifiable Credentials (SD-JWT VC) as defined in [[I-D.terbu-sd-jwt-vc](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#I-D.terbu-sd-jwt-vc)]. Person Identification Data (PID) defined in [[EUDIW.ARF](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#EUDIW.ARF)] is used.
