### ISSUE TITLE
"Holder Public Key Claim" should be "Key Binding Key Claim" or similar

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-selective-disclosure-jwt#352]
There is a subsection called "Holder Public Key Claim" that talks about the holder's public key. However, we usually now call this "Key Binding". 

We should modify that subsection to more generally talk about the key binding (public) key, but it would be fine to mention that this could be used for holder binding.

**Comment by rohan-wire** [comment]
> There is a subsection called "Holder Public Key Claim" that talks about the holder's public key. However, we usually now call this "Key Binding".
> 
> We should modify that subsection to more generally talk about the key binding (public) key, but it would be fine to mention that this could be used for holder binding.

A lot of folks are used to primarily using JWTs with symmetric keys, therefore they might be equally likely to expect an issuer binding as a holder binding. I think it is good to spell this out explicitly in section headings and in the first use of Key Binding.

**Comment by Sakurann** [comment]
agreed to rename "Holder Public Key Claim" section.
