### ISSUE TITLE
Confusing terminology

### ISSUE THREAD

**Issue by rohan-wire** [oauth-wg/oauth-selective-disclosure-jwt#358]
Hi,

Disclosure is used at least two ways in the document.

- to refer to the array containing the salt, (maybe name), and value.
- to refer to the base64url encoded string 

It's easy to understand how this could have happened, as both contain logically the same information. I propose explicitly calling these:

- **disclosure array**, and 
- **disclosure presentation**

I also propose calling the hash/digest of the disclosure the **disclosure digest** in full in every use. The only time we would use "disclosure" without one of these modifiers is talking about the process of disclosing in general.

As for the plaintext of the claims that can be disclosed, I propose **blinded claim**.

So the first paragraph of Section 4.1 would read:

An SD-JWT consists of:

- a signed JSON document, 
- a list of _disclosure presentations_ (each of which reveals a _blinded claim_), and 
- optionally an _issuer key binding_ (discussed in Section 4.3). 

The signed JSON document (the JWT body) contains plaintext claims; and _disclosure digests_, each of which either refers to a specific _blinded claim_ or is a _decoy_. The holder can include zero or more disclosure presentations without breaking the signature of the JWT body. The contents of the blinded claims cannot be modified, because the corresponding digest would no longer match any digest in the JWT body. Blinded claims can be individual object properties (key-value pairs) or array elements.

**Comment by danielfett** [comment]
This is appreciated! I agree that we should be more consistent with our terms. I'm not sure about "disclosure presentation" as "presentation" suggests a specific meaning. Maybe just "disclosure" and "disclosure contents" is fine.

**Comment by bc-pi** [comment]
The current document attempts to mostly use "Disclosure" to mean the base64url encoded string. I think that works okay. Places where it's referring to the decoded JSON array should be fixed to be more clear. So I think I agree that "disclosure" and where needed "disclosure contents" would be good.

**Comment by bc-pi** [comment]
PR #410 has editorial updates for more consistent treatment of a Disclosure vs the contents of a Disclosure
