### ISSUE TITLE
How to send SD-JWT and SD-JWT-R in a presentation

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#36]
Per https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/19#issuecomment-1144794055 in PR https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/19.

Two options how to the Holder sends SD-JWT and SD-JWT-R to the Verifier
1. as separate JWTs -> six period-separated elements
2. as one JWT (SD-JWT is a string inside SD-JWT-R) -> four period-separated elements

personally I am in favor of an option 2, also given the discussion in Issuer #37 on data structures potentially getting dissociated

**Comment by danielfett** [comment]
If the SD-JWT is a string inside the SD-JWT-R, this will create a larger data structure (base64 encoded base64).

**Comment by selfissued** [comment]
I agree with @danielfett that the double base64url-encoding resulting from option 2 is potentially problematic.

**Comment by Sakurann** [comment]
Current choice is to concatenate SD-JWT and HS-Disclosures JWT: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/155/files#diff-40bc3800dd9a7d4411799637caf0b01f82a01242d57264a2e4beb408c3835704R831

Noting that it is inconsistent with how vc-data-model defined for a vc to be sent inside a vp
