### ISSUE TITLE
Add 2.1 Abbreviations

### ISSUE THREAD

**Issue by sakimura** [oauth-wg/oauth-selective-disclosure-jwt#370]
Abbreviations appear in this document without first being defined, e.g., KB-JWT. 
It would make it easier for the readers if the document has an abbreviation section near the top of the document. 
Proposal: 
Create a new section 2.1 Abbreviation and collect all the abbreviations.

**Comment by Sakurann** [comment]
need to do after #394 is resolved to do a PR.

**Comment by bc-pi** [comment]
#394 does introduce more abbreviations where the terms are defined so might obsolete the need for a new section.

**Comment by bc-pi** [comment]
I'm gonna say https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/394 will sufficiently address the suggestion here.
