### ISSUE TITLE
quote claim name literals 

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#379]
Enclosing claim names (and similar things) in backticks (\`) in the markdown results in the text being enclosed in `<tt>` in the xml. In the html and pdf outputs of xml2rfc, that text enclosed in `<tt>` is output in a fixed-width font. Which is nice. However, in the txt output and subsequently the [htmlized version](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-06), there is nothing distinguishing such text (xml2rfc did previously surround with quotation marks but is no longer doing so). And even in the [html version](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-06.html) the fixed-width font with short values like claim names isn't always particularly distinguishing.  

All this is to say that I think a pass should be made through the whole markdown document to add (where appropriate) quotation marks around claim and header names and any other suitable items.

I've previously seen questions/comments about this from the RFC Editor as well as IESG and directorate reviews. So it wouldn't be a bad thing to do before getting to that stage.

**Comment by danielfett** [comment]
I remember similar discussions from RFC9449 and RFC9207 and AFAIR the outcome was to keep the current form (i.e., optimize for html and PDF output, not txt and htmlized txt).

**Comment by Sakurann** [comment]
I don't have a strong opinion, but keeping as-is seems ok, since backticks (`) are reflected in the html version

**Comment by selfissued** [comment]
I agree that we should be using backquotes to annotate identifiers in running text.  I oppose switching to doublequotes.

I asked the authors of XML2RFC v3 about the change in behavior for .txt files when the "new" (now a few years old) IETF RFC format was put in place.  They didn't seem concerned about it at the time - I believe being focused on formatted outputs such as HTML and PDF.

I don't think it would be productive for us to invent different conventions that try to contravene what the tools we're using do.

**Comment by danielfett** [comment]
Agreed in the call to stick to backticks.
