### ISSUE TITLE
More figures in Section 3 (Flow Diagram)

### ISSUE THREAD

**Issue by bifurcation** [oauth-wg/oauth-selective-disclosure-jwt#385]
It seems like some additional diagrams might be help folks understand some more important properties of this system.  For example, the fact that the Holder can only drop disclosures (not add them; only the Issuer can do that).  I've sketched some figures below, would be happy to make a PR with some ASCII art / [aasvg art](https://github.com/martinthomson/aasvg) if other folks think they would be useful.

(Note that I have used "Type 1 Thing" and "Type 2 Thing" as placeholders for "without KB" and "with KB" cf. #374)

<img width="435" alt="image" src="https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/75597/9c4d3f8f-f3c6-47b0-85b9-c3f3b75b2f0a">

<img width="435" alt="image" src="https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/75597/713b3705-692f-4781-9c41-693953a04dfd">

<img width="435" alt="image" src="https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/75597/a4992a59-5c03-4f55-95ec-9ed549f919a5">

<img width="569" alt="image" src="https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/75597/f1584815-c19b-4ea6-8181-facf9b86f5f8">

<img width="626" alt="image" src="https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/75597/0b4fbf20-35c8-41cc-bf4c-c4ff3698e8c4">

**Comment by danielfett** [comment]
This would need to be updated to the new terminology, but to be honest, I think those figures do not help a lot in understanding the spec. It seems that they would make great material for a blog post on SD-JWT though :-)

It seems that my co-authors agree, so I'll put "pending close" on this.
