### ISSUE TITLE
Example section headings

### ISSUE THREAD

**Issue by bifurcation** [oauth-wg/oauth-selective-disclosure-jwt#391]
The layout of these section delineations seems off.  There's an "Example 1" section header, but no other numbers.  Some examples are top-level, some are subordinate.  Is this intended?

<img width="301" alt="image" src="https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/75597/601c9cb4-ce7a-48d6-a31b-85a566d5f884">

**Comment by bc-pi** [comment]
> Is this intended?

Kinda.

[Appendix A](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-06.html#appendix-A) has additional examples with some of those other numbers.
![Screenshot 2023-12-04 at 3 44 32 PM](https://github.com/oauth-wg/oauth-selective-disclosure-jwt/assets/71398439/65ea440c-2518-43f7-a7fa-3eba88f57751)

And a few places refer back to "Example 1" by name. 

This all could probably be tidied up though.
