### ISSUE TITLE
burn the burning of private keys  

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#439]
As far as I know, the idea of burning private keys to facilitate repudiation or reduced data value didn't resonate with any of the audiences for whom it was intended.

I think the document would be better off without the paragraph copied below from https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-09.html#section-11.1-7 

And we might avoid some potentially difficult/confusing/painful/etc conversations in various latter stage IETF process steps. 

> If reliable and secure key rotation and revocation is ensured according to [Section 10.8](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-09.html#issuer_signature_key_distribution), Issuers may opt to publish expired or revoked private signing keys (after a grace period that ensures that the keys are not cached any longer at any Verifier). This reduces the value of any leaked credentials as the signatures on them can no longer be trusted to originate from the Issuer.

**Comment by bc-pi** [comment]
I'm told that my statement that it "didn't resonate with any of the audiences for whom it was intended" might be premature.

**Comment by selfissued** [comment]
I agree with deleting the text about publishing private keys.  Yes, it's a technique that could be used with SD-JWTs but it's in no way specific to SD-JWTs.  It could be used with normal JWTs, CWTs, SAML tokens, X.509 certs, etc.  It doesn't add to the specification to describe this here.

**Comment by bc-pi** [comment]
leaving this open with no action for the time being because, as Dr. @danielfett says, "it's complicated".

**Comment by Sakurann** [comment]
agreed to remove.
