### ISSUE TITLE
Mentions of KB-JWT that could be removed

### ISSUE THREAD

**Issue by srosenda** [oauth-wg/oauth-selective-disclosure-jwt#440]
The distinguishing of SD-JWT from SD-JWT+KB is a good clarifying change in -09. Some extra mentions of KB-JWT still remain that could probably removed:

In [5. ](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-09.html#section-5)[SD-JWT and SD-JWT+KB Data Formats](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-09.html#name-sd-jwt-and-sd-jwtkb-data-fo):

>An SD-JWT without Disclosures and without a KB-JWT

and

>An SD-JWT with Disclosures and without a KB-JWT

The "and without a KB-JWT" could be removed as there are separate examples for SD-JWT+KB and SD-JWT is now defined not to include KB-JWT.

**Comment by bc-pi** [comment]
Thanks @srosenda, PR #440 does exactly what you've suggested.

**Comment by srosenda** [comment]
👍 approved the PR (#441) too.
