### ISSUE TITLE
Give " a name

### ISSUE THREAD

**Issue by awoie** [oauth-wg/oauth-selective-disclosure-jwt#442]

**Comment by bc-pi** [comment]
By `Give " a name` here what @awoie means is that it'd be useful to have a name to refer to what we call the "processed SD-JWT payload" that's "passed to the application" [here](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-09.html#section-8.3-6) and is really the JSON after verification and processing and replacing `_sd` and `...` occurrences with the real values.

**Comment by awoie** [comment]
I created a issue here https://github.com/oauth-wg/oauth-selective-disclosure-jwt/issues/443. I don't know what happened with this issue. My apologies.

**Comment by bc-pi** [comment]
> I created a issue here #443. I don't know what happened with this issue. My apologies.

no apologies needed
