### ISSUE TITLE
holder key as DID

### ISSUE THREAD

**Issue by ThierryThevenet** [oauth-wg/oauth-selective-disclosure-jwt#463]
There is no reference about the possibility to use DIDs instead of cnf for the holder identifier
Is there any reason/recommendation not to use DIDs for the holder ?

**Comment by Sakurann** [comment]
that is out of scope for sd-jwt, since sd-jwt does not talk anything about the value of holder identifier. this is in scope for sd-jwt vc.

**Comment by bc-pi** [comment]
closing as out of scope
