### ISSUE TITLE
WGLC updates

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#464]
Placeholder issue to not forget to do appropriate updates resulting from WGLC 

https://mailarchive.ietf.org/arch/browse/oauth/?q=%22WGLC%20for%20SD-JWT%22

**Comment by bc-pi** [comment]
#472, #473, and #474 have some of this 

I think something for https://mailarchive.ietf.org/arch/msg/oauth/MN1d1ihchmOTcHVMsZ_RlOcZxRE/ would be good too

and of course #467 is there too

**Comment by Sakurann** [comment]
all merged or addressed

**Comment by bc-pi** [comment]
COMPLETELY REASONABLE changes made
