### ISSUE TITLE
sd_alg, _sd_alg - Option for claims reuse?

### ISSUE THREAD

**Issue by alenhorvat** [oauth-wg/oauth-selective-disclosure-jwt#468]
Dear,

First, I would like to express my gratitude for your excellent work on this project.

I have a question regarding the definitions of the following claims:

Claim Name: _sd
Claim Description: Digests of Disclosures for object properties

Claim Name: _sd_alg
Claim Description: Hash algorithm used to generate Disclosure digests and digest over presentation

Currently, the _sd claim is limited to digests of disclosures. However, there are other mechanisms available for blinding claims, such as Zero-Knowledge Proofs (ZKPs), signatures, and similar techniques. Since the design of _sd is quite robust and generic, would the authors consider broadening its definition to encompass these additional mechanisms?

Proposal:

Claim Name: _sd
Claim Description: Blinded (or hidden) claims as defined by the Selective Disclosure Algorithm
Additionally, similar to _sd_alg, it could be constructed from {sd-name}:{properties}.

Proposal:

Claim Name: _sd_alg
Claim Description: Selective disclosure algorithm name
For example, the algorithm name could be registered as something like: sd-jwt:sha-256.

Thank you very much for your time and consideration of this suggestion. I look forward to your feedback.

**Comment by Sakurann** [comment]
Hi Alen! Thank you for the suggestion. It feels a little immature to make a generalization for ZKP when those are not yet stably used with SD-JWT VCs and also feels like a violation of best/common practices by using the same claim for multiple purposes - for both pure sd-jwt mechanisms and zkp-based mechanisms.

It might be better and less breaking changes to later define a separate specification how to do sd-jwt with zkp

**Comment by alenhorvat** [comment]
Dear, Kristina.

I fully agree that other selective disclosure algorithms should be defined in separate specifications and in no way I'm asking to broaden the scope of this great work.

My question is simpler. Since the designs of _sd and _sd_alg are reusable with other (e.g., ZKP?) specifications, my question is if the definitions can be broadened.

If this results in a positive resolution, impact on the existing implementations is parsing of the _sd_alg claim that would define the full name of the sd algorithm, in this case something like sd-jwt:sha256 (or similar).

Thank you for your time and answers!

**Comment by danielfett** [comment]
Hi Alen,

We discussed this among the editors and came to the conclusion that introducing this kind of namespacing right now probably doesn't add value. We don't know yet how a future spec may or may not extend the _sd and _sd_alg claims (or the values therein). It may or may not work, but it certainly looks awkward in the meantime as SD-JWT is the only spec using/defining _sd and _sd_alg.

**Comment by alenhorvat** [comment]
Dear,

thank you for your time and considerations.

The issue can be closed.
