### ISSUE TITLE
Break down the examples in more granular steps

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#47]

**Comment by Sakurann** [comment]
requested by @christianpaquin
@danielfett is this something you could work on?

**Comment by danielfett** [comment]
I addressed this here: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/155/files#diff-40bc3800dd9a7d4411799637caf0b01f82a01242d57264a2e4beb408c3835704R800-R817

and here: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/155/files#diff-40bc3800dd9a7d4411799637caf0b01f82a01242d57264a2e4beb408c3835704R652-R668
