### ISSUE TITLE
The description of the SD-JWT+KB is confusing 

### ISSUE THREAD

**Issue by Denisthemalice** [oauth-wg/oauth-selective-disclosure-jwt#503]
Section 4:

>    An SD-JWT+KB is composed of
> 
>    *  an SD-JWT (i.e., an Issuer-signed JWT and zero or more
>       Disclosures), and
>    *  a Key Binding JWT.

 Change into:

>     A data structure for a SD-JWT with Disclosures and with key binding 
>     is composed of:
> 
>        *  an SD-JWT,
>        *  one or more Disclosures, and
>        *  a Key Binding JWT.

**Comment by AlexHodder** [comment]
An SD-JWT already includes Disclosures (zero or more). It is possible for an SD-JWT presentation to NOT include any Disclosures and still be valid.
