### ISSUE TITLE
More explanation on "precise JSON encoding can vary"

### ISSUE THREAD

**Issue by kushaldas** [oauth-wg/oauth-selective-disclosure-jwt#51]
Talking about https://www.ietf.org/archive/id/draft-fett-selective-disclosure-jwt-00.html#section-4.1.1.1-3

I think we should add one more line to explain that depending on the programming language & exact JSON library, the JSON encoded ordered array (which is the input to the hash function) may look different, but all are valid JSON. This also means the hash output may not be the same even for the same `salt` & `value`.

I spent 2 hours yesterday while totally missing a space in the JSON encoded string, which is not there in Rust JSON encoding, but in the  Python output.

**Comment by peppelinux** [comment]
I think that thi issue could be closed when this proposal will be approved (and implemented)
https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/27#issuecomment-1157732753

all the values will be a JSON Object and not escaped string
