### ISSUE TITLE
Hash Function Claim value case-sensitivity

### ISSUE THREAD

**Issue by spheroid** [oauth-wg/oauth-selective-disclosure-jwt#523]
In Section 4.1.1 Hash Function Claim it's stated that:

> The hash algorithm identifier MUST be a hash algorithm value from the "Hash Name String" column in the IANA "Named Information Hash Algorithm" registry [[IANA.Hash.Algorithms](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-13.html#IANA.Hash.Algorithms)] or a value defined in another specification and/or profile of this specification.

I've seen this reference and similar phrasing in other recent specifications and it's never indicated whether these values are case-sensitive or not. Perhaps this is fault of RFC 6920 not being explicit on the matter, but being vague here creates interop issues; I've already witnessed one regarding this very claim.

Should these values be considered case-sensitive or not?

**Comment by bc-pi** [comment]
I guess it doesn't say so explicitly but the intent is absolutely that the values be considered case-sensitive. 

We can maybe add a brief statement to that effect.

**Comment by bc-pi** [comment]
#525 adds one sentence indicating case-sensitivity.

**Comment by spheroid** [comment]
Excellent, thank you!

**Comment by lukasjhan** [comment]
Just for clarification, are sha-256 and SHA-256 different claim?

**Comment by bc-pi** [comment]
yes, sha-256 and SHA-256 are different

**Comment by lukasjhan** [comment]
> yes, sha-256 and SHA-256 are different

Good Thank you :)
