### ISSUE TITLE
Complete W3C VC/VP Example

### ISSUE THREAD

**Issue by tlodderstedt** [oauth-wg/oauth-selective-disclosure-jwt#59]
It unclear to me how the key for holder binding is represented and used in the example 4 in the appendix. Could you please add an explanation (perhaps JWT headers are required as well).

**Comment by tlodderstedt** [comment]
I recommend use of raw public keys (JWKs) in this example.

**Comment by Sakurann** [comment]
need to agree `sub_jwk` vs `cnf` re Issue #77

**Comment by Sakurann** [comment]
PR #162, PR #161
