### ISSUE TITLE
sd-jwt-r as signature algo

### ISSUE THREAD

**Issue by dtmcg** [oauth-wg/oauth-selective-disclosure-jwt#76]
this is an elegant solution to selective disclosure 👍 
question if the sd-jwt-r is modifed to contain the salts and payload value hash's (instead of the values), 
can the process used for generating the sd-jwt-r be considered a signature algo and be applied any JWT?

if the sd-jwt-r is b64 url encoded as a signature & appended to a plane old JWT 
this would make selective disclosure a function of the jwt alog. no additional objects need to be defined, this should make the solution easier to uptake in existing jwt libs where a supported algo can be added. 

steps 
- sd-jwt-r "signature" is generated for a JWT header and payload, as currently defined.
-  - the release contains the payload hashs and salt, then it is signed over as a JWT
- it is b64url encoded and appended as the signature
- when the holder wishes to share the JWT with a redacted payload they can do so by removing payload entities, re encode the json and append the same signature.

**Comment by Sakurann** [comment]
What does the issuer sign? 
If I understood correctly, you are swapping SD-JWT and SD-JWT-R as defined in the current draft, so that only claim values are included in SD-JWT-R and salt + hashes in SD-JWT. The issuer would have to sign over SD-JWT-R so that the holder can keep appending it integrity protected and your SD-JWT becomes unsigned SD-JWT-R because that is that the holder modifies when presenting.
Not sure what the new approaches achieves?

**Comment by danielfett** [comment]
I'm not sure I'm following the proposal. Maybe a concrete example would help.

**Comment by dtmcg** [comment]
> What does the issuer sign? If I understood correctly, you are swapping SD-JWT and SD-JWT-R as defined in the current draft, so that only claim values are included in SD-JWT-R and salt + hashes in SD-JWT. The issuer would have to sign over SD-JWT-R so that the holder can keep appending it integrity protected and your SD-JWT becomes unsigned SD-JWT-R because that is that the holder modifies when presenting. Not sure what the new approaches achieves?

yea mostly, what it achieves is that there are no new data types which need to understood, everything is in JWT with a longer signature, the verification of the jwt signature can be encapsulated into the jwt libs with a new algo handler

**Comment by danielfett** [comment]
If the SD-JWT-R contains the hashes and salts and is always released in full, we lose the selective disclosure property. The salts prevent guessing the plain-text values. Without them, it would be trivial, e.g., to guess a birth date (and many other claims as well).

**Comment by danielfett** [comment]
As far as I can tell, this has been obsoleted by the latest changes.
