### ISSUE TITLE
[Feature] JSON schema for SD-JWT

### ISSUE THREAD

**Issue by peppelinux** [oauth-wg/oauth-selective-disclosure-jwt#84]
Once we resolve [this issue](https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/27) we'll be able to define a validation schema (in draft and in code) for SD-JWT, SVC and SD-JWT-R if you agree

the python implementation will adopts pydantic if you agree

here some examples
https://github.com/italia/spid-cie-oidc-django/blob/main/spid_cie_oidc/entity/schemas/op_metadata.py#L84
https://github.com/italia/spid-cie-oidc-django/blob/main/docs/schemas/METADATA.md

**Comment by danielfett** [comment]
I do like the idea of having a JSON schema, and also generating it from Pydantic seems like a good idea!

**Comment by danielfett** [comment]
I think having the schemas in the annex makes sense.

**Comment by peppelinux** [comment]
Ok, I can do a proposal in https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/61 once we decide the final structure

**Comment by danielfett** [comment]
We have now once more updated the structure of SD-JWTs. @peppelinux Do you see an advantage of a JSON Schema for the current structure? There is not too much we could define in such a schema, I think.

**Comment by peppelinux** [comment]
I think that his schema is not relevant for the draft, could have been interesting inside the sample code in python but I doubt it is of any strategic use for SD-JWT
