### ISSUE TITLE
Is “Private key” appropriate term to use? 

### ISSUE THREAD

**Issue by sakimura** [oauth-wg/oauth-selective-disclosure-jwt#88]
# Comments
Perhaps a signing key is more appropriate if it is a “digitally signed document”

# Proposals
Replace "private key" with "signing key"

**Comment by Sakurann** [comment]
What is a concern with using `private key`? Both [JWA](https://www.rfc-editor.org/rfc/rfc7518.html) and [JWS](https://datatracker.ietf.org/doc/html/rfc7515) use `private key`.

**Comment by sakimura** [comment]
That was a comment I got from a cryptographer. I can ask them and get back to you.

**Comment by sakimura** [comment]
So, the rationale was that ISO's cryptography working group (SC27/WG2) has completely moved away from the terminology and decided to use function-based naming (signature key, verification key) instead of secrecy-based naming (private key, public key) as a private key does not necessarily have an ability to sign: you would have to specify a pairing algorithm with the word "private key" to make it sure that it is a signature key. 

Then, another cryptographer in the room told me that they prefer the term "secret key" that, while not all of them have abilities to sign, is a better name because then the reader/user will know that it has to be kept secret.

Another view given was that "private key" may imply a world where only Asymmetric and Symmetric crypto is there, which is not the case. 

My 2c.

**Comment by bc-pi** [comment]
To @Sakurann's point above, all the closely related specs use the term private key. rfc7518, rfc7800, rfc7520, rfc8037  being just a few others. It's a common term that's generally well understood. I believe it'd be a mistake to deviate from the norm.
