### ISSUE TITLE
Explain what is selective disclosure

### ISSUE THREAD

**Issue by sakimura** [oauth-wg/oauth-selective-disclosure-jwt#89]
# Comments
Concept of selective disclosure is not obvious for many readers so it needs to be explained

# Proposals
In the terms and definition, define it as follows

selective disclosure
process of disclosing a subset of claims contained in a claim set

**Comment by peppelinux** [comment]
Yes, this is not the first time I hear this question, it's not banal at all

**Comment by Sakurann** [comment]
PR #147

**Comment by Sakurann** [comment]
PR merged
