### ISSUE TITLE
Terms and definition formatting error

### ISSUE THREAD

**Issue by sakimura** [oauth-wg/oauth-selective-disclosure-jwt#90]
# Comments
While some of the definitions refer to other terms with numbers, the corresponding term is not numbered. 

# Proposals
Add numbers and reformat.

**Comment by danielfett** [comment]
I think we should remove the references with numbers since they are not required anyway.

The format we're using for the terms is a somewhat official one, using features provided by xml2rfc. Not sure if it is the best one, though.

**Comment by sakimura** [comment]
Removing the numbers is one way to remove the inconsistency and I am fine with it. It should be one way or another and be consistent. 

Having said that, the current format is hard to read, unfortunately. 

Also, I know it is not a norm in IETF, but relying on upper-casing for defined words and keywords is a bad idea, as they often do not translate. So, we should make sure that the defined terms would not appear in the main text in a dictionary meaning regardless of the case.

**Comment by danielfett** [comment]
We switched to a format that is also used in other published RFCs. The new format has a bit too much wide space, but otherwise works fine.
