### ISSUE TITLE
Should we move normative requirements from "Security Considerations" to the main text? 

### ISSUE THREAD

**Issue by sakimura** [oauth-wg/oauth-selective-disclosure-jwt#94]
# Comments
I know we sometimes do it, but I reckon that it is not a good practice to have normative requirements in the Security and Privacy considerations. 

# Proposal
Consider moving those MUSTs to the main text.

**Comment by Sakurann** [comment]
Is there a requirement from IETF to not have MUST in security considerations?

If not, I do not see a big problem keeping MUST in security/privacy considerations. specs like JWS/JWT that this spec builds on have MUSTs in normative sections: https://www.rfc-editor.org/rfc/rfc7515#section-10

**Comment by bc-pi** [comment]
AFAIK there are some IETF folks that prefer not to have normative language in security/privacy considerations but there's no definitive requirement as such. And to @Sakurann's point, there are lots of RFCs that do it. Moving those MUSTs to the main text would be unnecessary work and risk.
