### ISSUE TITLE
Underscore in front of `sd_release` and `sd_digests` claim names?

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-selective-disclosure-jwt#98]
See the discussion in https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/42

**Comment by peppelinux** [comment]
No please 😄
What an underscore would tell more or better regarding the nature of those claim names?

**Comment by danielfett** [comment]
We decided to keep the current claim names with the `sd_` prefix.
