### ISSUE TITLE
Consider using an HMAC instad of a prefix hash

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-selective-disclosure-jwt#99]
Neil wrote on the mailing list:

> Commitments to claim values are of the form HASH(SALT | CLAIM-VALUE), but this does not necessarily commit the sender to CLAIM-VALUE. In section 7.4, I think you need to say that HASH must be collision resistant - otherwise the user can find two (salt, claim-value) pairs that collide and get the issuer to sign one and then reveal the other pair to the downstream party.
> 
> The fact that HASH(SALT | CLAIM-VALUE) is vulnerable to length extension attacks is also troubling, even if I can’t see an immediate attack. But it’s a weird property that Bob, for example, could make a commitment to some extension of one of Alice’s claims without actually knowing her claim value.
> 
> You can address both of these issues by instead using a compactly committing PRF [1], such as HMAC- i.e., HMAC-HASH(SALT, CLAIM-VALUE) rather than simple prefix hash.

I think this make a lot of sense and we should consider using an HMAC instead.

**Comment by Sakurann** [comment]
+1
cc: @christianpaquin

**Comment by christianpaquin** [comment]
The spec shouldn't mandate or preclude a digest derivation function (DDF), but should require (MUST use) a collision- and preimage-resistant cryptographically secure one. Depending on the target application, a profile or deployment can mandate a particular DDF by requiring a particular hash function, KDF, or a more complex process (e.g., using truncated digests from strong hash functions to save space).

**Comment by Sakurann** [comment]
cc @bifurcation

**Comment by Sakurann** [comment]
yes, the issuer of SD-JWT can deny hashing the claims, but the issuer cannot deny signing over the whole SD-JWT. Or is the concern that the malicious verifier can change the claim values and regenerate the hashes, but issuer will not have the means to prove that it originally generated different hashes?

**Comment by Sakurann** [comment]
(on further discussion with @christianpaquin)

The spec should not mandate a particular digest derivation function, just like JWS does not mandate a signature algorithm. A random value used to generate a digest can be a salt (hash algorithm) or a key (HMAC). The former can be useful when there are constrains in space (e.g., to fit in a QR code), while the latter is more complex, but can help protect against brute-force attacks

We think it is a good idea to make it more explicit in the text that both approaches are allowed (currently it could be read as if HMAC is not).

**Comment by christianpaquin** [comment]
> The former can be useful when there are constrains in space (e.g., to fit in a QR code), while the latter is more complex, but can help protect against brute-force attacks

To clarify, all approaches must protect against brute-force attacks on the undisclosed attributes. If your target SD-JWT size is limited (e.g., in a QR embedding scenario), then you can sacrifice the salt and digest lengths by using a more expensive digest derivation function (e.g., PBKDF2-HMAC-SHA256-310000), as prototyped in [this project](https://github.com/christianpaquin/selective-disclosure). (Note: shorter digest lengths means truncating secure hash functions, not using weaker shorter ones.)

**Comment by Sakurann** [comment]
PR #149 

Section 7.5 already states `For the security of this scheme, the hash function is required to be preimage and collision resistant`.

**Comment by Sakurann** [comment]
PR merged
